# Regenerates addon/src/vx_ws_names.lua -- weaponskill id -> English name.
#
# Ashita's IResourceManager has GetSpellById and GetAbilityById but no
# weaponskill lookup, so this one table has to ship with the addon. Source is
# Metrics' resources/weapon_skills.lua, itself derived from Windower's.
#
# Only id and English name are kept: ~7KB instead of the 49KB original, and
# nothing else in that file is used. Every event also carries the raw actionId,
# so a lookup miss degrades to "#123" rather than losing information.
[CmdletBinding()]
param(
    [string] $Source = "C:\Users\thadl\OneDrive\Documents\Claude\resources\metrics\resources\weapon_skills.lua",
    [string] $Out
)

$root = $PSScriptRoot
if (-not $root) { $root = Split-Path -Parent $PSCommandPath }
if (-not $Out)  { $Out = Join-Path (Split-Path -Parent $root) 'src\vx_ws_names.lua' }

if (-not (Test-Path $Source)) {
    Write-Host "source not found: $Source" -ForegroundColor Red
    Write-Host "Metrics is not in this repo; see addon/PLAN.md for where it lives."
    exit 1
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('-- Generated by addon/tools/gen-ws-names.ps1 -- do not hand-edit.')
$lines.Add('--')
$lines.Add('-- Weaponskill id -> English name. Ashita''s IResourceManager exposes')
$lines.Add('-- GetSpellById and GetAbilityById but no weaponskill lookup, so this one')
$lines.Add('-- table has to ship. Derived from Windower''s weapon_skills.lua via Metrics.')
$lines.Add('')
$lines.Add('return {')

$n = 0
foreach ($l in (Get-Content $Source)) {
    $m = [regex]::Match($l, '^\s*\[(\d+)\]\s*=\s*\{id=(\d+),en="([^"]*)"')
    if ($m.Success) {
        $id = $m.Groups[1].Value
        $en = $m.Groups[3].Value -replace '"', '\"'
        $lines.Add(('    [{0}] = "{1}",' -f $id, $en))
        $n++
    }
}
$lines.Add('}')

[System.IO.File]::WriteAllLines($Out, $lines, (New-Object System.Text.UTF8Encoding $false))
"wrote $n weaponskills -> $Out"
