"""Regenerates addons/VibeXI/vx_ws_names.lua -- weaponskill id -> English name.

Ashita's IResourceManager has GetSpellById and GetAbilityById but no weaponskill
lookup, so this one table has to ship with the addon. Source is Metrics'
resources/weapon_skills.lua, itself derived from Windower's.

Only id and English name are kept: ~7KB instead of the 49KB original, and
nothing else in that file is used. Every event also carries the raw actionId, so
a lookup miss degrades to "#123" rather than losing information.

    python addon-dev/gen-ws-names.py

Writes CRLF, matching what the PowerShell generator produced, so regenerating an
unchanged table is a no-op in git rather than a whole-file diff.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # repo root
DEFAULT_SOURCE = Path(r'C:\Users\thadl\OneDrive\Documents\Claude\resources\metrics\resources\weapon_skills.lua')

ENTRY_RX = re.compile(r'^\s*\[(\d+)\]\s*=\s*\{id=(\d+),en="([^"]*)"')

HEADER = [
    '-- Generated by addon-dev/gen-ws-names.py -- do not hand-edit.',
    '--',
    "-- Weaponskill id -> English name. Ashita's IResourceManager exposes",
    '-- GetSpellById and GetAbilityById but no weaponskill lookup, so this one',
    "-- table has to ship. Derived from Windower's weapon_skills.lua via Metrics.",
    '',
    'return {',
]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--source', default=str(DEFAULT_SOURCE))
    ap.add_argument('--out', default=None, help='default: addons/VibeXI/vx_ws_names.lua')
    args = ap.parse_args(argv)

    source = Path(args.source)
    out = Path(args.out) if args.out else ROOT / 'addons' / 'VibeXI' / 'vx_ws_names.lua'

    if not source.is_file():
        print('source not found: %s' % source)
        print('Metrics is not in this repo; see addon-dev/PLAN.md for where it lives.')
        return 1

    lines = list(HEADER)
    n = 0
    for line in source.read_text(encoding='utf-8', errors='replace').splitlines():
        m = ENTRY_RX.match(line)
        if m:
            ws_id = m.group(1)
            en = m.group(3).replace('"', '\\"')
            lines.append('    [%s] = "%s",' % (ws_id, en))
            n += 1
    lines.append('}')

    # newline='' plus explicit \r\n: WriteAllLines put a line terminator after
    # every line including the last, and this file is CRLF in the working tree.
    with open(out, 'w', encoding='utf-8', newline='') as fh:
        for line in lines:
            fh.write(line + '\r\n')

    print('wrote %d weaponskills -> %s' % (n, out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
